### PR TITLE
Support of PlantUML.

### PR DESCRIPTION
**Pull request by noboruatkek**
I added some routines in main.py and model.py to eralchemy2 to generate PlantUML format output from database.

### CODE REVIEW

**Comment by maurerle** [comment]
Would you mind opening this PR against https://github.com/eralchemy/eralchemy ? That would be great!

**Comment by noboruatkek** [comment]
> Would you mind opening this PR against https://github.com/eralchemy/eralchemy ? That would be great!
Can I open a PR  on eralchemy directly ? or I should create a branch from from eralchemy before open PR?

**Comment by maurerle** [comment]
This repo is not a fork of eralchemy/eralchemy anymore, even though they share the same git history.
To do the PR against https://github.com/eralchemy/eralchemy, you need to:

* fork the https://github.com/eralchemy/eralchemy repo
* in your eralchemy2 copy, run `git remote add git@github.com:noboruatkek/eralchemy.git fork`
* `git merge fork/main` (or rebase, if you dare to handle the conflicts that way)
* `git push fork/main`
* create a PR against https://github.com/eralchemy/eralchemy

Or something like that, if you need help, just say so :)

**Comment by noboruatkek** [comment]
I created PR on [eralchemy/eralchemy](https://github.com/eralchemy/eralchemy).

**Pull request closed without merging**
