### PR TITLE
Finalize typing

### LINKED ISSUE #7: Add type hints
Hi,
since I use mypy eralchemy2 in my projects, it would be great if eralchemy2 could add type hints. I'm happy to give a PR a try.

### PR DESCRIPTION
**Pull request by kasium**
Closes #7

### CODE REVIEW

**Comment by kasium** [comment]
@maurerle can you please support? Should I put black, isort, mypy into tox? If yes, can you please give a hint? Else I need to install poetry and the dev dependencies in the CI. For that I know how to do it 😄

**Comment by maurerle** [comment]
Well good question.
Currently I added the extras dependencies to the extra `ci`
Tox does not install the dev-dependencies when installing the package

We could either
1. change `install_command` to `poetry install`, resulting in added dev-dependencies, and list the CI packages there
2. add `black, isort, mypy` to the tox deps, and add them to the dev-dependencies, resulting in two declarations of the same package
3. add `black, isort, mypy` to the `ci` extra packages, but then they must be added to normal dependencies with `optional: true` too (resulting in two declarations of the package)

I am quite new to poetry, so maybe there is an even better way I did not see. But I think, that the first option is the best one

**Comment by kasium** [comment]
I had the same issue in https://github.com/SAP/swagger-plugin-for-sphinx and went to install poetry with dev dependencies in the CI

**Comment by maurerle** [comment]
I see, but this does not really work with tox, as it manages a virtualenv itself and the testing dependency would be overwritten:
https://github.com/maurerle/eralchemy2/blob/main/pyproject.toml#L74

Furthermore if `poetry install` happens only in ci you have to do that in tox too prior to running `tox`, and I remember that something was weird that way yesterday..

So for me I think that 3 is the cleanest way in my case?

**Comment by kasium** [comment]
Mhm, sounds like a lot of duplication to me. One option would be to remove tox and just to test directly? What di you think about that? Also maybe https://github.com/tkukushkin/tox-poetry could help.

In the end please do what you think is the best for the project

**Comment by maurerle** [comment]
The problem I have is, that I'd like to test it once with SQLAlchemy < 1.4 and once above with the current version.
Somehow tox-poetry also seemed to just install all the dev-dependencies resulting in SQLAlchemy >=1.4

So if someone has a better way I am all ears but for now i just installed black and isort outside of tox and run it afterwards.

Thank you @kasium for the types!

**Comment by kasium** [comment]
@maurerle one approach would be to get rid of tox and let GitHub Actions install the correct python version

**Comment by maurerle** [comment]
the problem is not the different python versions but the two environments for SQLAlchemy:
https://github.com/maurerle/eralchemy2/blob/main/pyproject.toml#L74

Actually I am already using github actions to take care of the python version:
https://github.com/maurerle/eralchemy2/blob/main/.github/workflows/python-app.yml#L20

How would you suggest to add the two test cases with SQLAlchemy < 1.4 and >=1.4 without tox?

**Comment by kasium** [comment]
Beside using more flexible solutions like nox you can move that to the actions itself. So the action itself installs Sqlalchemy with the desired version  and then executes the tests

**Pull request merged**
